
# Task Three

## Intended Learning Outcomes

* Write a commented and reproducible script for data cleaning and exploratory analysis


## Clean data

* Your script should 

        - Clean column names
        - Fix typos and standardise text
        - Check for duplications and remove
        - Set factors
        - Check for any missing data and deal with it appropriately
        
* Make sure your script is reproducible: 
          
        - It should contain information on all packages needed
        - Run without errors or pauses to clean the dataset
        - Use tidyverse functions taught in the coursebook
        - Be clearly commented throughout
        
I strongly recommend that you compare your script with someone else on the course when completed. Work to suggest improvements to each others work. 


## The dataset

We are introduced to the fruitfly dataset Partridge and Farquhar (1981). From our understanding of sexual selection and reproductive biology in fruit flies, we know there is a well established 'cost' to reproduction in terms of reduced longevity for female fruitflies. The data from this experiment is designed to test whether increased sexual activity affects the lifespan of male fruitflies.

The flies used were an outbred stock, sexual activity was manipulated by supplying males with either new virgin females each day, previously mated females ( Inseminated, so remating rates are lower), or provide no females at all (Control). All groups were otherwise treated identically.

- type: type of female companion (virgin, inseminated, control(partners = 0))

- longevity: lifespan in days

- thorax: length of thorax in micrometres (a proxy for body size)

- sleep: percentage of the day spent sleeping

```{r, eval = F, echo = F}
dros <- read_csv("files/fruitfly.csv")

dros  |> add_whitespace(cols = "type", messiness = 0.01) |> change_case(type = "type") |> make_missing(cols = thorax, messiness = 0.05)) |>  duplicate_rows(0.05)
```


**Push your work to Github to complete**

