
# Task Two

## Intended Learning Outcomes

* Use AI to write code
* Critically evaluate the output of AI



## Here we go again 

Rather than giving you new exercises or content, your task is seemingly very simple: redo the dashboard from last week, but this time, **AI must write all of the code**. You can use any AI platform you'd like.

- Github copilot
- `chattr`
- chatbot windows e.g. chatgpt

The rationale behind this is that having worked through the report yourself, you will be intimately familiar with the dataset and the requirements of the assignment. This means that your ability to critically evaluate and check its output will be stronger than with a new dataset. This should (in theory) allow you to:

* Check whether it's actually done it right

* Understand how to engineer your prompts to get it closer to the solution if it's struggling

* Evaluate the suitability of alternative approaches to your original solution. 

## Set-up {#sec-setup-ai}

Create a separate project from your original practice report project to avoid any confusion.

## Starting advice

A few hints, tip, and rules to get you on your way:

* Although the dataset for the practice report isn't sensitive data, treat it as if it were. Even if the AI has the capability, don't upload the dataset. Instead run `str()` and `summary()` and describe the dataset to the AI so it knows the variables and the types of data.

> Note copilot only works when give permissions to your repository so this does not apply. 


* Check everything it produces. Just because it doesn't throw an error, doesn't mean it's right.

* Think about the specificity of your prompts. If you want it to produce solutions closer to our solution, tell it to use the `tidyverse`. If you'd like to see what other approaches it might take, don't give it a steer on packages (be mindful you might need to install some new packages).


## Keep a log

As you're progressing, makes notes on the following:

* What does it get right with ease?

* What does it get right with a bit of back-and-forth?

* What errors does it make? If you didn't know the dataset and hadn't worked through the report yourself, is there anything you think you may have missed that the AI got wrong?

* How does the code compare to your original solution?? Is there anything you think it did better? Is there anything you think you did better?

* Did you learn any new functions or approaches?

**Submit your individual chat histories, as a group compare your notes on the above and submit these as well in a markdown or plain text file**

::: {.callout-warning}

Teaching with and about AI is a brave new world. This exercise will be extremely useful for a number of reasons but we'd really appreciate any feedback on whether that's the case!

:::
