
# Task Four

## Intended Learning Outcomes

* Report an analysis and write-up for the Drosophila data

## Analysis

- Clearly describe your statistical approach: What type of model did you use? Why was it appropriate for your data?

- Explain your variables: What are the dependent and independent variables? Were any interactions or covariates included, and why?

- Detail the software and packages used: What tools did you use for data cleaning, modeling, and visualization?

- Mention model assumptions: How did you check for normality, homoscedasticity, or multicollinearity?

## Results

- State the main findings concisely: What were the key results, and were they statistically significant?

- Provide relevant statistical values: Include test statistics, degrees of freedom, P-values, confidence intervals, and effect sizes where applicable.

- Use tables and figures effectively: Summarize results using well-labeled tables and reference them in the text.

- Compare your findings: How do your results relate to your hypothesis? Did any unexpected patterns emerge?

- Interpret the biological significance: Beyond statistical significance, what do these findings mean in the context of your study?


```{r, echo = FALSE, fig.cap = " A scatter plot of longevity against body size across three treatments of differening male sexual activity. Fitted model slopes are from the reduced linear model (main effects only of thorax size, sleep and treatment group), with 95% confidence intervals, circles are individual data points. Marginal plots are density plot distributions for thorax length and longevity split by treatments."}

readRDS("dros_plot")

```
