
# Task Six

## Intended Learning Outcomes

* Flex your data visualisation skills

* **Work solo or in pairs** to make this project reproducible, clear and interpretable


## Data visuals

* The data - find a dataset, use an existing one - it can be anything you like! 

> But if you are struggling check out this R package: https://lter.github.io/lterdatasampler/

* Produce two figures - either in a Quarto doc (pdf preferred) or saved to png files

* One must be a scientific figure - and should have a figure legend (write this in a separate text file if not using Quarto). It must be Accurate, Beautiful and Clear

* The other must be the same data - but it should be the **worst** figure you can make - it should be misleading, ugly and unclear. 

* Make a clear note of how your **ugly** figure showcases the worst practices in data visualisation.

[Here is some inspiration for you](https://youtu.be/sJWmgCWgj-k)

## Scripts

-  Produce a project with clear directories, well-named scripts

-  Make sure scripts run without error, have clear comments and are well laid out

- Use a style guide to help you https://style.tidyverse.org/

- Use AI support if needed (declare all uses and record prompts)

- Make sure to proof and check all code produced by human or AI




