{
  "hash": "f3f3ff2cf10141c827acea8fff50c075",
  "result": {
    "engine": "knitr",
    "markdown": "# Poisson regression (for count data or rate data)\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n## Learning objectives:\n\n- Understand why linear models fail for count data\n\n- Recognise variance-mean relationships as the organising principle\n\n- Diagnose model misspecification vs distributional misfit\n\n- Choose between quasi-Poisson and negative binomial based on mechanism\n\n- Communicate results appropriately\n\n## Why count data needs different models\n\nCount or rate data are ubiquitous in the life sciences (e.g number of parasites per microlitre of blood, number of species counted in a particular area). These type of data are **discrete** and **non-negative**.\n\n- Count data characteristics: discrete, bounded at zero, often right-skewed\n\n- Linear model assumptions: continuous response, constant variance, unbounded predictions\n\nIn such cases assuming our response variable to be normally distributed is not typically sensible. \n\n\n\n## Example: Cuckoos\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/cuckoo.jpg){fig-align='center' width=100%}\n:::\n:::\n\n\nIn a study by [Kilner *et al.* (1999)](http://www.nature.com/nature/journal/v397/n6721/abs/397667a0.html), the authors studied the begging rate of nestlings in relation to total mass of the brood of **reed warbler chicks** and **cuckoo chicks**.\n\nThe question of interest is:\n\n> How does nestling mass affect begging rates between the different species?\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<a href=\"https://github.com/UEABIO/5023B/blob/dev/files/cuckoo.csv\">\n<button class=\"btn btn-success\"><i class=\"fa fa-save\"></i> Download Cuckoo data as csv</button>\n</a>\n```\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhead(cuckoo)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|      Mass| Beg|Species |\n|---------:|---:|:-------|\n|  9.637522|   0|Cuckoo  |\n| 10.229151|   0|Cuckoo  |\n| 13.103706|   0|Cuckoo  |\n| 15.217391|   0|Cuckoo  |\n| 16.231884|   0|Cuckoo  |\n| 20.120773|   0|Cuckoo  |\n\n</div>\n:::\n:::\n\n\nThe data columns are:\n\n* **Mass**: nestling mass of chick in grams\n* **Beg**: begging calls per 6 secs\n* **Species**: Warbler or Cuckoo\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(cuckoo, aes(x = Mass, y = Beg, colour = Species)) + \n  geom_point(size = 3, alpha = 0.6) +\n  scale_colour_manual(values = c(\"darkorange\", \"steelblue\")) +\n  labs(x = \"Nestling mass (g)\", \n       y = \"Begging calls per 6 seconds\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](poisson_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThere seem to be a relationship between mass and begging calls and it could be different between species. It is tempting to fit a linear model to this data. \n\nIn fact, this is what the authors of the original paper did; **reed warbler chicks** (solid circles, dashed fitted line) and  **cuckoo chick** (open circles, solid fitted line):\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/original.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n## When Linear models fail\n\nLet us display the model diagnostics plots for a linear model.\n\n:::{.task}\n::::{.task-header}\nFit a linear model\n::::\n::::{.task-container}\n\nFit a linear model with interaction:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncuckoo_lm <- lm(Beg ~ Mass * Species, data = cuckoo)\n\nsummary(cuckoo_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Beg ~ Mass * Species, data = cuckoo)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-31.4366  -5.3476   0.8151   5.8992  22.8429 \n\nCoefficients:\n                    Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         -20.5057     7.7542  -2.644   0.0111 *  \nMass                  1.6384     0.3086   5.310 2.93e-06 ***\nSpeciesWarbler       14.1325     8.5983   1.644   0.1069    \nMass:SpeciesWarbler  -0.4891     0.3530  -1.386   0.1724    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 10.95 on 47 degrees of freedom\nMultiple R-squared:  0.6116,\tAdjusted R-squared:  0.5868 \nF-statistic: 24.67 on 3 and 47 DF,  p-value: 9.805e-10\n```\n\n\n:::\n:::\n\n\nExamine diagnostics:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncheck_model(cuckoo_lm, detrend = FALSE)\n```\n:::\n\n\n**Discussion questions:**\n- What does the residuals vs fitted plot show?\n- Can this model predict negative begging calls?\n- Is the assumption of constant variance met?\n\n::::\n:::\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\nThe residuals vs fitted plot shows clear heteroscedasticity—variance increases with fitted values. The Q-Q plot shows deviation from normality. Most critically, the model predicts **negative begging calls** for small nestlings:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Generate predictions\npredictions_lm <- emmeans(cuckoo_lm, \n                          specs = ~ Mass + Species,\n                          at = list(Mass = seq(0, 40, by = 5))) |>\n  as_tibble()\n\n# Check for negative predictions\npredictions_lm |> \n  filter(emmean < 0)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Mass|Species |     emmean|       SE| df|   lower.CL|   upper.CL|\n|----:|:-------|----------:|--------:|--:|----------:|----------:|\n|    0|Cuckoo  | -20.505662| 7.754204| 47| -36.105109| -4.9062148|\n|    5|Cuckoo  | -12.313633| 6.326688| 47| -25.041287|  0.4140212|\n|   10|Cuckoo  |  -4.121603| 4.968631| 47| -14.117200|  5.8739939|\n|    0|Warbler |  -6.373125| 3.715268| 47| -13.847281|  1.1010303|\n|    5|Warbler |  -0.626695| 3.006921| 47|  -6.675841|  5.4224508|\n\n</div>\n:::\n:::\n\n\nLinear models are inappropriate when:\n1. Response is bounded (cannot be negative)\n2. Variance changes systematically with mean\n3. Relationship is inherently non-linear\n\n\n</div>\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nperformance::check_model(cuckoo_lm, \n                         detrend = FALSE)\n```\n:::\n\n\n\n## Poisson GLM—modelling counts explicitly\n\n### The Poisson distribution and log-link\n\n\nThe Poisson distribution lets us model count data explicitly.\n\n\nInstead of assuming constant variance, Poisson models explicitly link variance to the mean:\n\n**Poisson distribution properties:**\n- Discrete, non-negative integers\n- Single parameter λ (rate)\n- Mean = λ\n- Variance = λ (key assumption)\n\n* **Discrete** variable, defined on the range $0, 1, \\dots, \\infty$.\n* A single ***rate*** parameter $\\lambda$, where $\\lambda > 0$.\n* **Mean** = $\\lambda$  \n* **Variance** = $\\lambda$\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](poisson_files/figure-html/unnamed-chunk-13-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n**The log link:**\n\n$$\n\\begin{aligned}\nY_i & \\sim \\text{Poisson}(\\lambda_i) \\\\\n\\log(\\lambda_i) & = \\beta_0 + \\beta_1 X_i\n\\end{aligned}\n$$\n\nThis constrains predictions to be positive and models the exponential mean-response relationship naturally present in many biological count processes.\n\n**What the log link does:**\n- Ensures predicted counts are always positive (since e^x > 0 for all x)\n- Creates multiplicative effects on the original scale\n- Models proportional rather than additive changes\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/poisson.png){fig-align='center' fig-alt='Poisson distribution on an exponential line' width=80%}\n:::\n:::\n\n\n\n## Fitting a Poisson GLM \n\nWe start with an **additive model** (parallel slopes):\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncuckoo_glm_add <- glm(Beg ~ Mass + Species, \n                      data = cuckoo, \n                      family = poisson(link = \"log\"))\n\nsummary(cuckoo_glm_add)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Beg ~ Mass + Species, family = poisson(link = \"log\"), \n    data = cuckoo)\n\nCoefficients:\n               Estimate Std. Error z value Pr(>|z|)    \n(Intercept)    0.811318   0.121372   6.685 2.32e-11 ***\nMass           0.078835   0.003663  21.520  < 2e-16 ***\nSpeciesWarbler 0.038744   0.072049   0.538    0.591    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 970.08  on 50  degrees of freedom\nResidual deviance: 442.81  on 48  degrees of freedom\nAIC: 620.59\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\nGenerate predictions on the response scale:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npredictions_poisson <- emmeans(cuckoo_glm_add,\n                               specs = ~ Mass + Species,\n                               at = list(Mass = seq(0, 40, by = 5)),\n                               type = \"response\") |>\n  as_tibble()\n\nggplot(predictions_poisson, aes(x = Mass, y = rate, colour = Species)) +\n  geom_line(linewidth = 1) +\n  geom_point(data = cuckoo, aes(y = Beg), alpha = 0.5) +\n  scale_colour_manual(values = c(\"darkorange\", \"steelblue\")) +\n  labs(x = \"Nestling mass (g)\", \n       y = \"Begging calls per 6 seconds\",\n       title = \"Poisson GLM: Additive model\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](poisson_files/figure-html/unnamed-chunk-16-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n**Key observations:**\n- No negative predictions\n- Variance increases with mean (heteroscedasticity is expected and appropriate)\n- Exponential curves fit the biological relationship better than straight lines\n\n:::{.task}\n::::{.task-header}\nExamine model diagnostics\n::::\n::::{.task-container}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncheck_model(cuckoo_glm_add, \n            residual_type = \"normal\",\n            detrend = FALSE)\n```\n\n::: {.cell-output-display}\n![](poisson_files/figure-html/unnamed-chunk-17-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n**Focus on:**\n1. Q-Q plot: Are deviance residuals approximately normal?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncheck_model(cuckoo_glm_add, \n            residual_type = \"normal\",\n            detrend = FALSE,\n            check = \"qq\")\n```\n:::\n\n\n2. Residuals vs fitted: Is there remaining pattern?\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncheck_model(cuckoo_glm_add, \n            residual_type = \"normal\",\n            detrend = FALSE,\n            check = \"homogeneity\")\n```\n:::\n\n\n3. **Dispersion check**: What does this plot show?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncheck_model(cuckoo_glm_add, \n            residual_type = \"normal\",\n            detrend = FALSE,\n            check = \"overdispersion\")\n```\n:::\n\n\nCalculate dispersion manually:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndispersion_add <- cuckoo_glm_add$deviance / cuckoo_glm_add$df.residual\ndispersion_add\n\n# performance model check\ncheck_overdispersion(cuckoo_glm_add)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.225245\n# Overdispersion test\n\n       dispersion ratio =   7.446\n  Pearson's Chi-Squared = 357.394\n                p-value = < 0.001\n```\n\n\n:::\n:::\n\n\n**Discussion:** The dispersion ratio is [~7-9]. What might cause variance to exceed the Poisson assumption?\n\n\n<div class='webex-solution'><button>Possible Solutions</button>\n\n\n- A misspecified model - are we missing key variables or ways in which existing variables might interact?\n\n- Genuine overdispersion - our data does not fit the expectations of a Poisson distribution\n\n\n</div>\n\n\n::::\n:::\n\n\n## Diagnosing and addressing model misspecification\n\n### Understanding overdispersion sources\n\nBefore applying \"fixes\" for overdispersion, ask: **have we correctly specified the mean function?**\n\n### Hypothesis: The interaction is missing\n\nLook at the data :\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(cuckoo, aes(x = Mass, y = Beg, colour = Species)) + \n  geom_point(size = 3, alpha = 0.6) +\n  scale_colour_manual(values = c(\"darkorange\", \"steelblue\")) +\n  labs(x = \"Nestling mass (g)\", \n       y = \"Begging calls per 6 seconds\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](poisson_files/figure-html/unnamed-chunk-22-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nWarbler calling rate increases more slowly with mass than cuckoo rate.\n\n**If we force parallel slopes when they're actually different:**\n\n- We mis-specify the mean structure\n\n- Create systematic residual patterns \n\n- Artificially inflate variance\n\n- Generate spurious overdispersion\n\nThis is **unmodelled heterogeneity**—a primary cause of apparent overdispersion.\n\n:::{.task}\n::::{.task-header}\nAdd the interaction term\n::::\n::::{.task-container}\n\nFit the model with Mass × Species interaction:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncuckoo_glm_int <- glm(Beg ~ Mass * Species, \n                      data = cuckoo, \n                      family = poisson(link = \"log\"))\n\nsummary(cuckoo_glm_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Beg ~ Mass * Species, family = poisson(link = \"log\"), \n    data = cuckoo)\n\nCoefficients:\n                     Estimate Std. Error z value Pr(>|z|)    \n(Intercept)          0.334475   0.227143   1.473  0.14088    \nMass                 0.094847   0.007261  13.062  < 2e-16 ***\nSpeciesWarbler       0.674820   0.259217   2.603  0.00923 ** \nMass:SpeciesWarbler -0.021673   0.008389  -2.584  0.00978 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 970.08  on 50  degrees of freedom\nResidual deviance: 436.05  on 47  degrees of freedom\nAIC: 615.83\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\n\n\n\nCompare dispersion between models:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndispersion_comparison <- tibble(\n  Model = c(\"Additive (no interaction)\", \n            \"Interaction included\"),\n  Dispersion = c(\n    cuckoo_glm_add$deviance / cuckoo_glm_add$df.residual,\n    cuckoo_glm_int$deviance / cuckoo_glm_int$df.residual\n  )\n)\n\ndispersion_comparison\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Model                     | Dispersion|\n|:-------------------------|----------:|\n|Additive (no interaction) |   9.225245|\n|Interaction included      |   9.277570|\n\n</div>\n:::\n:::\n\n\n**Critical question:** Has dispersion reduced?\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncheck_overdispersion(cuckoo_glm_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Overdispersion test\n\n       dispersion ratio =   7.724\n  Pearson's Chi-Squared = 363.036\n                p-value = < 0.001\n```\n\n\n:::\n:::\n\n\n::::\n:::\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\nDispersion has not meaningfully reduced. Adding the biologically meaningful interaction has **captured substantial variance** by better modelling the mean structure.\n\n**Key insight:** Much \"overdispersion\" is actually **model misspecification**. Always investigate whether:\n1. Important covariates are missing\n2. Relationships are non-linear (consider polynomials)\n3. Interactions exist between predictors\n\nHowever, residual overdispersion remains (φ̂ ≈ [1.5-2]), suggesting variance still exceeds the mean even with correct mean specification.\n\n\n</div>\n\n\n###  Comparing model predictions\n\nCompare the fits between these models:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(cuckoo_glm_add, cuckoo_glm_int)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Resid. Df| Resid. Dev| Df| Deviance|  Pr(>Chi)|\n|---------:|----------:|--:|--------:|---------:|\n|        48|   442.8118| NA|       NA|        NA|\n|        47|   436.0458|  1| 6.765991| 0.0092911|\n\n</div>\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Generate predictions for both models\npred_additive <- emmeans(cuckoo_glm_add,\n                         specs = ~ Mass + Species,\n                         at = list(Mass = seq(0, 40, by = 1)),\n                         type = \"response\") |>\n  as_tibble() |>\n  mutate(Model = \"Additive\")\n\npred_interaction <- emmeans(cuckoo_glm_int,\n                            specs = ~ Mass + Species,\n                            at = list(Mass = seq(0, 40, by = 1)),\n                            type = \"response\") |>\n  as_tibble() |>\n  mutate(Model = \"Interaction\")\n\npredictions_combined <- bind_rows(pred_additive, pred_interaction)\n\nggplot(predictions_combined, aes(x = Mass, y = rate, colour = Species)) +\n  geom_point(data = cuckoo, aes(y = Beg), alpha = 0.4) +\n  geom_line(aes(linetype = Model), linewidth = 1) +\n  scale_colour_manual(values = c(\"darkorange\", \"steelblue\")) +\n  labs(x = \"Nestling mass (g)\",\n       y = \"Begging calls per 6 seconds\",\n       title = \"Model comparison: Additive vs Interaction\") +\n  theme_minimal() +\n  theme(legend.position = \"right\")+\n  facet_wrap(~Model)\n```\n\n::: {.cell-output-display}\n![](poisson_files/figure-html/unnamed-chunk-27-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\nThe interaction model captures the different slopes between species—warblers' calling rate increases more slowly with mass.\n\n\n\n### Addressing remaining model checks\n\nOverdispersion may not have been addressed - but are any of the other model checks improved?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncheck_model(cuckoo_glm_int, \n            residual_type = \"normal\",\n            detrend = FALSE)\n```\n\n::: {.cell-output-display}\n![](poisson_files/figure-html/unnamed-chunk-28-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n## Remaining overdispersion: Two approaches\n\nEven with the interaction, dispersion > 1. This residual variance could arise from:\n\n1. **Other unmeasured covariates** (brood size, hunger level, time of day)\n2. **Individual heterogeneity** (some chicks intrinsically call more)\n3. **Measurement variation** (observer counting differences)\n4. **Clustering** (multiple obs per nest—not applicable here)\n5. **Zero inflation** Another biological process determines presence of calling at all\n\nWe cannot measure everything. Two philosophical approaches for handling extra-Poisson variance:\n\n### Quasi-Poisson: Agnostic approach\n\n**Philosophy:** \"Variance exceeds the mean by some factor φ, but I won't specify *why*\"\n\n**What it does:**\n- Estimates dispersion parameter from data: Var = φμ\n- Multiplies standard errors by √φ\n- Widens confidence intervals proportionally\n- No distributional assumption beyond scaled Poisson\n\n**Advantages:**\n- Simple, honest acknowledgment of uncertainty\n- No additional assumptions\n\n**Limitations:**\n- Cannot do likelihood-based model comparison (no AIC)\n- Doesn't model the mechanism\n- Assumes dispersion is constant across the range of fitted values\n\n### Negative binomial: Mechanistic approach\n\n**Philosophy:** \"Individuals have different underlying rates drawn from a gamma distribution\"\n\n**What it assumes:**\n- True rates (λᵢ) vary between observations\n- This heterogeneity follows a gamma distribution\n- Produces variance = μ + μ²/θ (quadratic relationship)\n\n**Advantages:**\n- Explicit mechanistic model\n- Allows AIC-based model comparison\n- Models variance structure directly\n\n**Limitations:**\n- Requires specific variance-mean relationship\n- Additional parameter to estimate\n- May not fit if variance structure differs from quadratic\n\n**Neither is universally \"better\"**—choose based on:\n- Your beliefs about what generates heterogeneity\n- Whether you need model comparison\n- How variance scales with the mean\n\n:::{.task}\n::::{.task-header}\nFit quasi-Poisson and negative binomial models\n::::\n::::{.task-container}\n\n**Quasi-Poisson:**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncuckoo_quasi <- glm(Beg ~ Mass * Species, \n                    data = cuckoo, \n                    family = quasipoisson(link = \"log\"))\n\nsummary(cuckoo_quasi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Beg ~ Mass * Species, family = quasipoisson(link = \"log\"), \n    data = cuckoo)\n\nCoefficients:\n                    Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          0.33448    0.63129   0.530    0.599    \nMass                 0.09485    0.02018   4.700  2.3e-05 ***\nSpeciesWarbler       0.67482    0.72043   0.937    0.354    \nMass:SpeciesWarbler -0.02167    0.02332  -0.930    0.357    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for quasipoisson family taken to be 7.7242)\n\n    Null deviance: 970.08  on 50  degrees of freedom\nResidual deviance: 436.05  on 47  degrees of freedom\nAIC: NA\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\nNote the dispersion parameter estimate.\n\n:::{.callout-important}\n\n- The quasilikelihood model *just* adds a dispersion term to our SE so model fits do not change\n\n:::\n\n**Negative binomial:**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(MASS)\ncuckoo_negbin <- glm.nb(Beg ~ Mass * Species, \n                        data = cuckoo)\n\nsummary(cuckoo_negbin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm.nb(formula = Beg ~ Mass * Species, data = cuckoo, init.theta = 0.9028849768, \n    link = log)\n\nCoefficients:\n                    Estimate Std. Error z value Pr(>|z|)    \n(Intercept)         -2.21359    0.91829  -2.411  0.01593 *  \nMass                 0.19140    0.03463   5.527 3.26e-08 ***\nSpeciesWarbler       3.09452    0.99572   3.108  0.00188 ** \nMass:SpeciesWarbler -0.11269    0.03868  -2.913  0.00358 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for Negative Binomial(0.9029) family taken to be 1)\n\n    Null deviance: 98.183  on 50  degrees of freedom\nResidual deviance: 60.376  on 47  degrees of freedom\nAIC: 357.3\n\nNumber of Fisher Scoring iterations: 1\n\n              Theta:  0.903 \n          Std. Err.:  0.226 \n\n 2 x log-likelihood:  -347.296 \n```\n\n\n:::\n:::\n\n\nNote the theta parameter (θ)—this controls how much variance exceeds the mean.\n\n::::\n:::\n\n### Model diagnostics\n\nLet's compare models using AIC:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nAIC(cuckoo_glm_int, cuckoo_negbin)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|               | df|      AIC|\n|:--------------|--:|--------:|\n|cuckoo_glm_int |  4| 615.8282|\n|cuckoo_negbin  |  5| 357.2955|\n\n</div>\n:::\n:::\n\n\n\nThe negative binomial has lower AIC—typically interpreted as \"better fit.\" But AIC measures *predictive performance*, not whether *model assumptions are met*.\n\n**Critical check: Does the model capture the variance structure?**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncheck_model(cuckoo_negbin, detrend = FALSE)\n```\n:::\n\n\n\n**Focus on two key diagnostics:**\n\n1. **Dispersion check (Misspecified dispersion?)** \n2. **Posterior predictive check**\n\n:::{.task}\n::::{.task-header}\nExamine the negative binomial diagnostics\n::::\n::::{.task-container}\n\nLook carefully at:\n\n**The dispersion plot:**\n- Does the grey line (predicted variance-mean relationship) match the points (observed variance)?\n\n- Is the negative binomial variance function (Var = μ + μ²/θ) appropriate?\n\n**The posterior predictive check:**\n- Do the light blue lines (simulated data from the model) match the dark blue line (observed data)?\n\n- Are there systematic discrepancies?\n\n**Discussion questions:**\n\n1. What pattern do you see in the dispersion plot?\n\n2. Does the model over-predict or under-predict variance?\n\n3. What does the posterior predictive check suggest about model fit?\n\n\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n**Dispersion plot observation:**\n\nThe negative binomial predicts that variance should increase **quadratically** with the mean (the curved grey line). However, the observed variance (points) **increases more slowly than predicted**—almost linearly rather than quadratically.\n\nThis means the negative binomial is **over-modelling** the variance structure. It's trying to fit a strongly accelerating variance pattern when the data show more modest heterogeneity.\n\n**Posterior predictive check observation:**\n\nThe simulated data from the negative binomial (light blue lines) show **different distributional properties** than the observed data (dark blue line). Specifically:\n- The model may generate more extreme values than observed\n- The shape of the distribution doesn't match well\n- There's systematic misfit, not just random variation\n\n**What this means:**\n\nDespite having lower AIC, the negative binomial **imposes an inappropriate variance structure** on these data. The quadratic variance-mean relationship is too strong for the actual pattern of heterogeneity.\n\n\n</div>\n\n\n::::\n:::\n\nIs the dispersion now adequately modelled?\n\n\n\n\n## How do modelling decisions affect inference? \n\nA critical question: does the interaction between Mass and Species matter? Let's see how this answer changes depending on our modelling decisions.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Extract coefficients with confidence intervals\ncoef_poisson <- tidy(cuckoo_glm_int, conf.int = TRUE) |>\n  mutate(Model = \"Poisson\")\n\ncoef_quasi <- tidy(cuckoo_quasi, conf.int = TRUE) |>\n  mutate(Model = \"Quasi-Poisson\")\n\ncoef_negbin <- tidy(cuckoo_negbin, conf.int = TRUE) |>\n  mutate(Model = \"Negative Binomial\")\n\ncoef_comparison <- bind_rows(coef_poisson, coef_quasi, coef_negbin) |>\n  filter(term == \"Mass:SpeciesWarbler\") |>  \n  dplyr::select(Model, estimate, std.error, conf.low, conf.high, p.value)\n\ncoef_comparison\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Model             |   estimate| std.error|   conf.low|  conf.high|   p.value|\n|:-----------------|----------:|---------:|----------:|----------:|---------:|\n|Poisson           | -0.0216734| 0.0083890| -0.0382142| -0.0053172| 0.0097787|\n|Quasi-Poisson     | -0.0216734| 0.0233150| -0.0682230|  0.0234428| 0.3573333|\n|Negative Binomial | -0.1126887| 0.0386837| -0.2369783| -0.0077036| 0.0035788|\n\n</div>\n:::\n:::\n\n\n**Visualise the uncertainty:**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(coef_comparison, aes(x = Model, y = estimate)) +\n  geom_point(size = 4) +\n  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), \n                width = 0.2, linewidth = 1.2) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", \n             colour = \"red\", linewidth = 1) +\n  labs(y = \"Interaction coefficient (Mass:SpeciesWarbler)\",\n       x = \"\",\n       title = \"Same data, different inferences\") +\n  theme_minimal(base_size = 14) +\n  theme(panel.grid.major.x = element_blank()) +\n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](poisson_files/figure-html/unnamed-chunk-34-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n### The problem: significance depends on model choice\n\nLook at the p-values:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncoef_comparison |>\n  mutate(\n    Significant = if_else(p.value < 0.05, \"Yes\", \"No\"),\n    `CI crosses zero` = if_else(conf.low < 0 & conf.high > 0, \"Yes\", \"No\")\n  ) |>\n  dplyr::select(Model, estimate, p.value, Significant, `CI crosses zero`)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Model             |   estimate|   p.value|Significant |CI crosses zero |\n|:-----------------|----------:|---------:|:-----------|:---------------|\n|Poisson           | -0.0216734| 0.0097787|Yes         |No              |\n|Quasi-Poisson     | -0.0216734| 0.3573333|No          |Yes             |\n|Negative Binomial | -0.1126887| 0.0035788|Yes         |No              |\n\n</div>\n:::\n:::\n\n\n**What we observe:**\n- Point estimates are identical for Poisson and Quasipoisson ( around -0.02)\n\n- The Poisson model gives P < 0.05 (interaction \"significant\")\n\n- The Quasi-Poisson model gives P > 0.05 (interaction \"not significant\")\n\n- The Negative Binomial falls somewhere between - *but* also estimates the relationship as slightly different\n\n**The uncomfortable truth:** Whether you conclude the interaction \"matters\" depends on which model you chose. This is a **borderline result**.\n\n\n### Critical discussion\n\n\n1. The Poisson model ignores overdispersion—its P-value is anti-conservative (too small). Should we trust it?\n\n2. The Quasi-Poisson corrects for overdispersion conservatively—but does P = 0.06 really mean \"no effect\" compared to P = 0.04?\n\n3. If you were reviewing this paper, what would you want the authors to report?\n\n4. Does the magnitude of the effect (coefficient ≈ -0.02) matter more than whether P < 0.05?\n\n\n\n### How to think about borderline results\n\n**Don't:**\n- Report only the model that gives P < 0.05\n- Conclude \"no effect\" if P > 0.05 with one model\n- Pretend the threshold at 0.05 is meaningful\n- Hide the fact that inference is model-dependent\n\n**Do:**\n- Report results from the most appropriate model\n- Acknowledge uncertainty honestly\n- Focus on effect size and confidence intervals, not just P-values\n- Consider biological significance alongside statistical significance\n\n\n\n:::{.callout-important}\n**The key principle:**\n\nWhen results are borderline, **report the effect size, confidence interval, and biological interpretation** rather than fixating on whether P < 0.05. Statistical significance is a continuum of evidence, not a binary threshold.\n\nA result with P = 0.06 and a biologically meaningful effect size warrants the same scientific attention as one with P = 0.04.\n:::\n\n\n### Practical implications for your research\n\nWhen you encounter borderline results:\n\n1. **Report transparently:** Show that inference depends on modelling assumptions\n\n2. **Contextualise statistically:** \n   - \"The 95% CI marginally includes zero\"\n   - \"Evidence for interaction is modest (P = 0.06)\"\n   - Not: \"There was no interaction\" or \"The interaction failed to reach significance\"\n\n3. **Contextualise biologically:**\n   - Is a 2% difference per gram body mass biologically meaningful?\n   - Does it accumulate to substantial differences over the observed range?\n   - Does it align with theory about begging behaviour?\n\n4. **Consider power:**\n   - With n = 48, we have limited power to detect modest interactions\n   - CIs are wide—we'd be uncertain even with larger samples\n   - This is weak evidence for *or* against the interaction\n\n5. **Avoid HARKing:**\n   - If you predicted the interaction a priori, P = 0.06 is worth discussing\n   - If you're data mining, it's probably noise\n   - Don't retrofit hypotheses to P-values\n   \n   \n## Reporting Results\n\n### Visualising the biological pattern regardless of P-value\n\n**Principles for effective GLM figures:**\n\n1. Show raw data with sufficient transparency\n\n2. Display model predictions with uncertainty\n\n3. Use the response scale (not log scale)\n\n4. Make the biological pattern immediately clear\n\n5. Avoid chart junk—every element should serve a purpose\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n## Final model predictions\npredictions_final <- emmeans(cuckoo_quasi,\nspecs = ~ Mass + Species,\nat = list(Mass = seq(0, 40, by = 0.5)),\ntype = \"response\") |>\nas_tibble()\n\nfig_main <- ggplot(predictions_final,\naes(x = Mass, y = rate,\ncolour = Species, fill = Species)) +\ngeom_ribbon(aes(ymin = asymp.LCL, ymax = asymp.UCL),\n            alpha = 0.15, colour = NA) +\n# Mean estimate\ngeom_line(linewidth = 1.2) +\n# Raw data\ngeom_point(data = cuckoo,\naes(y = Beg),\nsize = 2.5,\nalpha = 0.6) +\n\nscale_colour_manual(values = c(\"Cuckoo\" = \"darkorange\", \"Warbler\" = \"steelblue\"),\nlabels = c(\"Cuckoo\", \"Reed warbler\")\n\n) +\nscale_fill_manual(values = c(\"Cuckoo\" = \"darkorange\", \"Warbler\" = \"steelblue\"),\nlabels = c(\"Cuckoo\", \"Reed warbler\")\n\n) +\nscale_x_continuous(breaks = seq(0, 40, by = 10)) +\nscale_y_continuous(breaks = seq(0, 100, by = 10)) +\n\n  labs(\nx = \"Nestling mass (g)\",\ny = \"Begging calls per 6 seconds\",\ncolour = NULL,\nfill = NULL\n) +\ntheme_minimal(base_size = 12)\n\n\nfig_main\n```\n\n::: {.cell-output-display}\n![](poisson_files/figure-html/unnamed-chunk-36-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n### Writing the Results section\n\n**The goal**: Tell the biological story whilst providing necessary statistical support.\n\n**Avoid:**\n- Leading with statistics (\"There was a significant effect of mass, z = 5.2, P < 0.001...\")\n- Reporting every coefficient\n- Using jargon without explanation\n- Ignoring effect sizes\n\n**Prefer:**\n- Lead with biology, support with statistics\n- Report interpretable effects (rate ratios on response scale)\n- Include confidence intervals\n- Contextualise the magnitude\n\n**Example results text:**\n\n**Version 1: Statistics-first (poor)**\n\n\"There was a significant effect of mass on begging calls (t = 4.7, P < 0.001, quasi-Poisson GLM). There was a not a significant effect of species (t = 0.35, P = 0.35). The interaction between mass and species was not significant (t = -.93, P = 0.357).\"\n\n**Version 2: Effect-focused (better)**\n\n\"Begging call rates increased with nestling mass, we found no significant evidence that this relationship differed between species (Mass × Species interaction: t = -.93, P = 0.357, quasi-Poisson GLM). In our model all chicks were associated with a 10% increase in calling rate (rate ratio 1.1 [95% CI: 1.06–1.15]) for each gram increase in mass.\n\n\n**Version 3: Biologically contextualised (best)**\n\n\"Begging call rates increased with nestling mass for both species. There was weak evidence that this relationship differed between species as our interaction term was significant under the Poisson GLM (Mass × Species interaction: z = -2.58, P = 0.009) but not when accounting for overdispersion with quasi-Poisson (Mass × Species interaction: t(47) = -.93, P = 0.357). Given this uncertainty, we proceeded with an additive model assuming parallel slopes for both species.\n\nAcross the observed mass range, each gram increase in mass was associated with a 8% increase in calling rate (rate ratio: 1.08 [95% CI: 1.07–1.09]). Reed warblers called at higher rates (1.04 [95% CI 0.9 - 1.2]) than cuckoos after accounting for body mass differences but this was not statistically significant  (Species effect: t(47) = 0.54, P = 0.69). \n\n\n**What makes Version 3 effective:**\n- Starts with the biological pattern\n- Provides concrete predictions at meaningful mass values\n- Gives effect sizes in interpretable units (% increase per gram)\n- Acknowledges statistical uncertainty honestly\n- Links to biological theory\n\n### Extracting key values for reporting\n\nHere's how to get the numbers you need:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Exponentiated coefficients (rate ratios)\ntidy(cuckoo_quasi, exponentiate = TRUE, conf.int = TRUE)\n\n# Additive model\n\ncuckoo_quasi_add <- glm(Beg ~ Mass + Species, family = poisson(link = \"log\"), data = cuckoo)\n\ntidy(cuckoo_quasi_add, exponentiate = TRUE, conf.int = TRUE)\n\n# Predictions at specific mass values\npred_key_masses <- emmeans(cuckoo_quasi,\n                           specs = ~ Species + Mass,\n                           at = list(Mass = c(10, 40)),\n                           type = \"response\") |>\n  as_tibble()\n\npred_key_masses\n\n# Rate ratios: how much does calling increase per gram?\n# For cuckoos: exp(β_Mass)\n# For warblers: exp(β_Mass + β_Mass:SpeciesWarbler)\n\n# Formal test of interaction\ndrop1(cuckoo_quasi, test = \"F\")\n```\n:::\n\n\n\n### Common mistakes to avoid\n\n**Mistake 1: Reporting on the wrong scale**\n\n❌ \"The coefficient for mass was 0.077 (SE = 0.015, P < 0.001)\"\n\nThis is on the **log scale**—readers can't interpret it.\n\n✅ \"Each gram increase in mass was associated with an 8% increase in calling rate (rate ratio: 1.08 [95% CI: 1.05–1.11], z = 5.2, P < 0.001)\"\n\n**Mistake 2: Forgetting to mention overdispersion**\n\n❌ \"We used Poisson regression...\"\n\n✅ \"We used quasi-Poisson regression to account for overdispersion (φ̂ = 1.6)...\"\n\n**Mistake 3: Binary thinking about P-values**\n\n❌ \"The interaction was not significant (P = 0.057), therefore species do not differ in their responses to mass.\"\n\n✅ \"The interaction was marginally non-significant (P = 0.057), though the point estimate suggests warblers increase calling more slowly with mass (rate ratio: 0.98 [95% CI: 0.96–1.00]).\"\n\n**Mistake 4: Ignoring effect magnitude**\n\n❌ \"Mass had a significant effect on calling rate (P < 0.001)\"\n\n✅ \"Calling rate increased 8% per gram of mass [95% CI: 6–11%], corresponding to a 4.5-fold increase across the observed mass range\"\n\n**Mistake 5: Not showing the data**\n\n❌ Only showing the model prediction lines\n\n✅ Showing raw data points alongside predictions\n\n\n## Summary: What this section teaches\n\n1. **Model choice affects inference** when results are borderline—this is normal, not a failure\n\n2. **P = 0.049 vs P = 0.051 is not a meaningful distinction**—effect sizes and CIs matter more\n\n3. **Statistical significance ≠ biological importance**—a modest effect can be biologically interesting even if P > 0.05\n\n4. **Transparency builds trust**—show sensitivity to model assumptions rather than hiding it\n\n5. **Report honestly**—acknowledge uncertainty rather than forcing conclusions into binary categories\n\nThis is the most important statistical lesson: **how to think when results aren't clean**.\n\n\n### What we didn't cover: When simple models aren't enough\n\nOur quasi-Poisson model captured the variance-mean relationship adequately for inference about mass and species effects. However, careful observers will have noticed it under-predicts zeros—particularly for cuckoos at low masses.\n\n**Zero-inflation** occurs when you observe more zeros than any Poisson-family model can accommodate. This suggests two processes:\n\n1. A \"structural zero\" process (chick is sleeping, satiated, or not motivated)\n\n2. A \"count\" process (when motivated, how often does the chick call?)\n\n**Zero-inflation models** (ZIP, ZINB) explicitly model both processes:\n\n- Which variables predict being in the \"always zero\" state?\n\n- Which variables predict calling rate when active?\n\n**For example**, you might hypothesise:\n- Species might affect propensity to call\n- Body mass predicts calling rate when active\n\nThis requires substantially more data and careful biological thinking about what generates \"structural\" vs \"sampling\" zeros.\n\n**When is this critical?**\n- Research focuses on presence/absence of behaviour\n- Zeros dominate the dataset (>40-50%)\n- Predictions at low rates are crucial\n- You have mechanistic hypotheses about zero-generating processes\n\n**When can you proceed without it?**\n- Zeros are modest (<20-30% of observations)\n- Research questions concern patterns across non-zero counts\n- Main effects are robust despite zero under-prediction\n- You acknowledge the limitation transparently\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncuckoo |>\n    group_by(Species) |>\n    summarise(\n        n = n(),\n        n_zeros = sum(Beg == 0),\n        prop_zeros = n_zeros / n,\n        pct_zeros = prop_zeros * 100\n    )\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Species |  n| n_zeros| prop_zeros| pct_zeros|\n|:-------|--:|-------:|----------:|---------:|\n|Cuckoo  | 17|       9|  0.5294118|  52.94118|\n|Warbler | 34|       4|  0.1176471|  11.76471|\n\n</div>\n:::\n:::\n\n\n\nWhilst addressing zero-inflation would refine predictions, it doesn't change our core conclusions about how calling scales with mass or differs between species.\n\n",
    "supporting": [
      "poisson_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/font-awesome-6.5.2/js/script.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}