{
  "hash": "73757d1a8b1e270a078950e65bea7043",
  "result": {
    "engine": "knitr",
    "markdown": "# Foundations of Mixed Modelling\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n\n\n## Introduction\n\nAll our previous analyses assumed **independence** between observations. However, this assumption breaks down when:\n\n- We make repeated measurements on individuals or groups\n- We repeat experiments across different times or locations\n- Samples are processed in batches (different days, machines, technicians)\n- We use paired or matched designs\n\nWhen observations are grouped in this way, measurements within the same group tend to be more similar to each other than to measurements from different groups. Ignoring this structure leads to incorrect conclusions.\n\n## What is a Mixed Model?\n\nMixed models extend linear regression by including two types of effects:\n\n- **Fixed effects**: Variables we are directly interested in testing (e.g., treatment, dose, temperature). We estimate specific coefficients for these predictors.\n\n- **Random effects**: Grouping factors that create non-independence (e.g., individual, batch, field site). Rather than estimating separate coefficients for each group, we estimate how much groups vary around an overall average.\n\nThink of random effects as accounting for \"nuisance variation\" - variation we need to control for, but are not primarily interested in.\n\n::: {.callout-note}\n## When to use random effects\n\nUse a variable as a random effect when:\n\n- It is categorical with multiple levels (typically 5+)\n- You want to generalise beyond the specific groups in your study\n- Group sample sizes are unbalanced or some data are missing\n- You are not interested in comparing specific groups to each other\n:::\n\n\n\n### The Study\n\nThis dataset comes from replicate feeding experiments investigating how *Spodoptera frugiperda* (Fall Army Worm) larvae respond to plant defensive compounds. Larvae were reared on artificial diet containing different concentrations of the benzoxazinoid DIMBOA, and researchers measured a composite detoxification capacity index.\n\n**Why replicate experiments?** Larval responses can vary substantially between experimental batches due to factors like:\n\n- Slight differences in rearing conditions\n- Variation in larval age at testing\n- Day-to-day environmental fluctuations\n- Unmeasured genetic variation between cohorts\n\nBy running multiple independent replicates, researchers ensure their findings are robust and generalisable.\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/Spodoptera_frugiperda.jpg){fig-align='center' fig-alt='Fall Army Worm' width=60%}\n:::\n:::\n\n\n**Variables:**\n\n- `benzo_um`: Toxin concentration in diet (µM)\n\n- `detox_exp`: Detoxification capacity index (higher = stronger response)\n\n- `group`: Experimental replicate (1–5)\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<a href=\"https://raw.githubusercontent.com/Philip-Leftwich/Oct-Intro-Analytics/refs/heads/dev/files/benzo.csv\">\n<button class=\"btn btn-success\"><i class=\"fa fa-save\"></i> Download benzoxazinoid data as csv</button>\n</a>\n```\n\n:::\n:::\n\n\n### Visualising the Problem\n\nIf we ignore the group structure and plot all data together, we see an apparent positive relationship:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(benzo_data, aes(x = benzo_um, y = detox_exp)) +\n  geom_point(alpha = 0.6) +\n  labs(\n    x = \"Toxin concentration (µM)\",\n    y = \"Detoxification capacity\"\n  ) +\n  geom_smooth(method = \"lm\", se = TRUE)\n```\n\n::: {.cell-output-display}\n![All data pooled together, ignoring experimental batch](intro-mixed-model_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nHowever, when we colour points by experimental batch, a more complex picture emerges:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(benzo_data, aes(x = benzo_um, y = detox_exp, colour = group)) +\n  geom_point(alpha = 0.6) +\n  labs(\n    x = \"Toxin concentration (µM)\",\n    y = \"Detoxification capacity\"\n  ) +\n  theme(legend.position = \"right\")\n```\n\n::: {.cell-output-display}\n![Data coloured by experimental batch reveals group-level variation](intro-mixed-model_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThe groups differ substantially in their baseline detoxification capacity. Some batches show higher average responses than others, even at the same toxin concentration.\n\n::: {.task}\n:::: {.task-header}\nExplore group differences\n::::\n:::: {.task-container}\n\nCreate a boxplot showing how detoxification capacity varies between experimental batches.\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(benzo_data, aes(x = group, y = detox_exp, fill = group)) +\n  geom_boxplot() +\n  labs(\n    x = \"Experimental batch\",\n    y = \"Detoxification capacity\"\n  ) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![Baseline detoxification varies substantially between batches](intro-mixed-model_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nGroup 2 has consistently higher detoxification capacity, whilst Group 4 is substantially lower. This batch-to-batch variation must be accounted for.\n\n\n</div>\n\n\n::::\n:::\n\n## Three Approaches Compared\n\n### Approach 1: Pooled Model (Ignoring Groups)\n\nThis treats all observations as independent:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npooled_model <- lm(detox_exp ~ benzo_um, data = benzo_data)\nsummary(pooled_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = detox_exp ~ benzo_um, data = benzo_data)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-37.23 -12.11  -2.36  11.00  44.53 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  21.0546     1.6490  12.768   <2e-16 ***\nbenzo_um      2.5782     0.2854   9.034   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 16.96 on 428 degrees of freedom\nMultiple R-squared:  0.1602,\tAdjusted R-squared:  0.1582 \nF-statistic: 81.62 on 1 and 428 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n**Problem**: The standard errors are artificially small because we are treating 430 observations as independent when they are not. This inflates our confidence in the estimate.\n\n### Approach 2: Fixed-Effect Model\n\nInclude group explicitly as a predictor:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfixed_model <- lm(detox_exp ~ benzo_um + group, data = benzo_data)\nsummary(fixed_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = detox_exp ~ benzo_um + group, data = benzo_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-26.3011  -6.3665  -0.3373   6.6295  31.5816 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  11.7808     1.2931   9.111  < 2e-16 ***\nbenzo_um      2.0242     0.1704  11.883  < 2e-16 ***\ngroup2        3.8771     1.4214   2.728 0.006642 ** \ngroup3       36.3036     1.4286  25.412  < 2e-16 ***\ngroup4        9.2323     1.4215   6.495 2.33e-10 ***\ngroup5        8.0609     2.0922   3.853 0.000135 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 10.05 on 424 degrees of freedom\nMultiple R-squared:  0.7077,\tAdjusted R-squared:  0.7042 \nF-statistic: 205.3 on 5 and 424 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n**When this works well:**\n\n- Few groups (< 5)\n- Large, balanced sample sizes per group\n- You want to make inferences about these specific batches only\n\n**Limitations:**\n\n- Cannot generalise to future batches\n- Uses many degrees of freedom estimating group differences\n- Struggles with unbalanced designs or missing data\n\n### Approach 3: Mixed-Effects Model\n\nModel group-to-group variation as random:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(lmerTest)\n\nmixed_model <- lmer(detox_exp ~ benzo_um + (1 | group), data = benzo_data)\nsummary(mixed_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: detox_exp ~ benzo_um + (1 | group)\n   Data: benzo_data\n\nREML criterion at convergence: 3224.4\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-2.61968 -0.63654 -0.03584  0.66113  3.13597 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n group    (Intercept) 205      14.32   \n Residual             101      10.05   \nNumber of obs: 430, groups:  group, 5\n\nFixed effects:\n            Estimate Std. Error       df t value Pr(>|t|)    \n(Intercept)  23.2692     6.4818   4.1570    3.59   0.0215 *  \nbenzo_um      2.0271     0.1703 424.0815   11.90   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n         (Intr)\nbenzo_um -0.131\n```\n\n\n:::\n:::\n\n\nThe notation `(1|group)` specifies a **random intercept** - each group has its own baseline value, but the slope (effect of toxin) is assumed constant.\n\n**Random Effects:**\n```\n Groups   Name        Variance Std.Dev.\n group    (Intercept) 205.0    14.32   \n Residual             101.0    10.05   \n```\n\nThis tells us that groups differ in their intercepts with a standard deviation of 14.32. The proportion of remaining variance explained by groups is:\n```\n205 / (205 + 101) = 0.67\n```\n\nSo experimental batch accounts for 67% of the variation not explained by toxin concentration.\n\n**Fixed Effects:**\n```\n            Estimate Std. Error      df t value Pr(>|t|)    \n(Intercept)  19.8348     6.5163  4.3098   3.044   0.0339 *  \nbenzo_um      2.0261     0.1701 424.0888  11.909  < 2e-16 ***\n```\n\nThe effect of toxin concentration is 2.03 units increase in detoxification per µM increase in toxin (95% CI: 1.69–2.36).\n\n### Comparing Standard Errors\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|Approach     |term        | estimate| std.error|\n|:------------|:-----------|--------:|---------:|\n|Pooled       |(Intercept) |   21.055|     1.649|\n|Pooled       |benzo_um    |    2.578|     0.285|\n|Fixed Effect |(Intercept) |   11.781|     1.293|\n|Fixed Effect |benzo_um    |    2.024|     0.170|\n|Mixed Model  |(Intercept) |   23.269|     6.482|\n|Mixed Model  |benzo_um    |    2.027|     0.170|\n\n\n:::\n:::\n\n\nNotice:\n\n- **Pooled**: Intercept SE is unrealistically small (ignores batch variation)\n- **Fixed**: Smallest SE, but only describes Group 1\n- **Mixed**: Larger intercept SE (correctly reflects batch uncertainty), reasonable slope SE\n\n## When Are Mixed Models Actually Necessary?\n\nLooking at our results, you might notice something important: the slope estimates are nearly identical across all three approaches:\n\n- Pooled model: 2.58 (SE = 0.29)\n- Fixed-effect model: 2.04 (SE = 0.17)\n- Mixed model: 2.03 (SE = 0.17)\n\nThe fixed-effect and mixed models give essentially the same answer for the toxin effect. **This is common**. Mixed models often don't change your conclusions about fixed effects dramatically—so when is the extra complexity worth it?\n\n### Mixed models provide clear advantages when:\n\n1. **Unbalanced designs**: Some groups have far fewer observations than others. Notice Group 5 has only 30 observations whilst Groups 1–4 have 100 each. The fixed-effect model treats Group 5's estimate as equally reliable, whilst the mixed model appropriately reflects this uncertainty.\n\n2. **Generalisation**: We want to generalise to future experimental batches, not just describe these five specific ones. Random effects model batch-to-batch variability, allowing predictions for new batches.\n\n3. **Missing data**: If some groups have missing predictor values, mixed models handle this elegantly whilst fixed-effect models struggle.\n\n4. **Many groups**: With 10+ groups, fixed-effect models consume many degrees of freedom. Mixed models are more parsimonious.\n\n5. **Hierarchical structure matters**: When group-level variance is substantial (here, batch explains 67% of residual variance), acknowledging this structure improves model interpretation even if slope estimates barely change.\n\n### Fixed-effect models are perfectly adequate when:\n\n1. **Few groups** (< 5) with balanced designs\n2. **Large sample sizes** per group  \n3. **No interest in generalisation** beyond these specific groups\n4. **Complete data** with no missing values\n\n**For this dataset**: Either the fixed-effect or mixed model would be defensible. The mixed model is preferable because (a) we have unbalanced groups, and (b) we want to generalise to future experiments, not just describe these five batches. But if you only cared about these specific batches, the fixed-effect model would be simpler and yield the same scientific conclusion.\n\n::: {.callout-warning}\n## Don't use mixed models blindly\n\nMixed models are not always better than simpler alternatives. Use them when the data structure requires it, not because they seem more sophisticated. If a fixed-effect model answers your research question adequately, the added complexity of random effects may be unnecessary.\n:::\n\n## Making Predictions\n\nWe can make predictions from mixed models using tools you're already familiar with. The `emmeans` package works for mixed models just as it does for standard linear models, producing estimated marginal means averaged across random effects:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(emmeans)\n\nemmeans(mixed_model, \n        specs = \"benzo_um\", \n        at = list(benzo_um = c(0, 2.5, 5, 7.5, 10)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n benzo_um emmean   SE   df lower.CL upper.CL\n      0.0   23.3 6.48 4.14     5.51     41.0\n      2.5   28.3 6.44 4.03    10.52     46.2\n      5.0   33.4 6.43 4.00    15.56     51.2\n      7.5   38.5 6.44 4.04    20.65     56.3\n     10.0   43.5 6.48 4.14    25.78     61.3\n\nDegrees-of-freedom method: kenward-roger \nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\nThese predictions represent the **population-average** response—what we'd expect for a \"typical\" experimental batch. The values are averaged across all groups, with uncertainty reflecting both within-group variation and between-group differences.\n\nWe can visualise these marginal means:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemmeans(mixed_model, \n        specs = \"benzo_um\", \n        at = list(benzo_um = seq(0, 10, 0.5))) |>\n  as.data.frame() |>\n  ggplot(aes(x = benzo_um, y = emmean)) +\n  geom_ribbon(aes(ymin = lower.CL, ymax = upper.CL), alpha = 0.3) +\n  geom_line(linewidth = 1) +\n  labs(\n    x = \"Toxin concentration (µM)\",\n    y = \"Detoxification capacity\",\n    title = \"Population-average predictions\"\n  )\n```\n\n::: {.cell-output-display}\n![Estimated marginal means at different toxin concentrations](intro-mixed-model_files/figure-html/unnamed-chunk-14-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n### Group-specific predictions\n\nHowever, mixed models allow us to do something standard linear models cannot: predict responses for **specific groups**. Whilst `emmeans` focuses on population averages, the `ggeffects` package can show predictions for individual batches:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggeffects)\n\n# Population-level predictions (equivalent to emmeans)\nggpredict(mixed_model,\n  terms = \"benzo_um\",\n  type = \"fixed\"\n) |>\n  plot(show_data = TRUE) +\n  labs(\n    x = \"Toxin concentration (µM)\",\n    y = \"Detoxification capacity\"\n  )\n```\n\n::: {.cell-output-display}\n![Predicted relationship accounting for batch variation (population average)](intro-mixed-model_files/figure-html/unnamed-chunk-15-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThis shows the average (population-level) relationship with 95% confidence intervals—essentially the same information as our `emmeans` plot above, just formatted differently.\n\nTo see group-specific predictions:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpredict(mixed_model,\n  terms = c(\"benzo_um\", \"group\"),\n  type = \"random\"\n) |>\n  plot(show_data = TRUE) +\n  facet_wrap(~group) +\n  labs(\n    x = \"Toxin concentration (µM)\",\n    y = \"Detoxification capacity\"\n  )\n```\n\n::: {.cell-output-display}\n![Group-specific predictions showing batch-to-batch variation](intro-mixed-model_files/figure-html/unnamed-chunk-16-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nEach panel shows predictions for a specific batch, illustrating how baseline detoxification differs whilst the slope remains similar. These conditional predictions account for each group's specific intercept whilst maintaining the common slope estimated by the fixed effect.\n\n::: {.callout-note}\n## `emmeans` vs `ggpredict`\n\n- Use **`emmeans`** when you want numerical marginal means, pairwise comparisons, or contrasts (as in previous chapters). It focuses on population-average estimates.\n\n- Use **`ggpredict`** when you want to visualise predictions or show group-specific effects. It can produce both population-level and conditional (group-specific) predictions.\n\n- Both produce equivalent population-level estimates for fixed effects—the difference is in presentation and the ability to show group-specific predictions.\n:::\n\n## Model Fit\n\nWe can assess overall model performance using R² values:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(MuMIn)\nr.squaredGLMM(mixed_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            R2m       R2c\n[1,] 0.09949133 0.7027654\n```\n\n\n:::\n:::\n\n\n- **R²m (marginal)**: Variance explained by fixed effects alone (toxin concentration) = 10%\n- **R²c (conditional)**: Variance explained by full model (fixed + random effects) = 70%\n\nThe large difference shows that experimental batch explains substantial variation beyond the toxin effect.\n\n## Checking Model Assumptions\n\nMixed models make the same assumptions as linear models (linearity, homoscedasticity, normality of residuals), plus an additional assumption: that random effects are normally distributed. \n\nThe `performance` package provides diagnostic plots for mixed models:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(performance)\ncheck_model(mixed_model, detrend = FALSE)\n```\n:::\n\n\n**Key diagnostics to examine:**\n\n- **Posterior Predictive Check**: Do simulated data from the model resemble observed data?\n- **Linearity**: Is the relationship between predictors and response linear?\n- **Homogeneity of Variance**: Is residual spread constant across fitted values?\n- **Normality of Residuals**: Do residuals follow a normal distribution?\n- **Normality of Random Effects**: Do group-level intercepts follow a normal distribution?\n\nIf assumptions are violated, you may need to transform variables, add polynomial terms, or use a generalised linear mixed model (GLMM).\n\n::: {.callout-note}\n## DHARMa package\n\nThe `performance` package uses simulated residuals from the `DHARMa` package for mixed model diagnostics. This approach is more reliable than examining raw residuals, particularly for detecting heteroscedasticity and non-normality.\n:::\n\n## Presenting Results\n\n### Interpreting `summary()` output\n\nThe `summary()` function provides essential information for understanding and reporting your model:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(mixed_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: detox_exp ~ benzo_um + (1 | group)\n   Data: benzo_data\n\nREML criterion at convergence: 3224.4\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-2.61968 -0.63654 -0.03584  0.66113  3.13597 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n group    (Intercept) 205      14.32   \n Residual             101      10.05   \nNumber of obs: 430, groups:  group, 5\n\nFixed effects:\n            Estimate Std. Error       df t value Pr(>|t|)    \n(Intercept)  23.2692     6.4818   4.1570    3.59   0.0215 *  \nbenzo_um      2.0271     0.1703 424.0815   11.90   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n         (Intr)\nbenzo_um -0.131\n```\n\n\n:::\n:::\n\n\n**Random effects section** shows:\n- Between-group variance (how much groups differ)\n- Residual variance (within-group variation)\n- Standard deviations for each variance component\n\n**Fixed effects section** shows:\n- Coefficient estimates\n- Standard errors\n- Degrees of freedom (calculated using Satterthwaite approximation)\n- *t*-values and *p*-values\n\n### Model fit statistics\n\nThe `MuMIn` package calculates R² values for mixed models:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(MuMIn)\nr.squaredGLMM(mixed_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            R2m       R2c\n[1,] 0.09949133 0.7027654\n```\n\n\n:::\n:::\n\n\n- **R²m (marginal)**: Proportion of variance explained by fixed effects alone\n- **R²c (conditional)**: Proportion of variance explained by the complete model (fixed + random effects)\n\nThe difference between R²c and R²m indicates how much variance the random effects explain.\n\n### Creating tables\n\nThe `sjPlot` package produces publication-ready tables:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(sjPlot)\n\ntab_model(mixed_model, \n          show.re.var = TRUE,\n          show.icc = TRUE,\n          show.r2 = TRUE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"3\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">detox exp</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Estimates</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">23.27</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">10.53&nbsp;&ndash;&nbsp;36.01</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">benzo um</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">2.03</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.69&nbsp;&ndash;&nbsp;2.36</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td colspan=\"4\" style=\"font-weight:bold; text-align:left; padding-top:.8em;\">Random Effects</td>\n</tr>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">&sigma;<sup>2</sup></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">101.01</td>\n</tr>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">&tau;<sub>00</sub> <sub>group</sub></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">205.00</td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">ICC</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.67</td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">N <sub>group</sub></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">5</td>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"3\">430</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">Marginal R<sup>2</sup> / Conditional R<sup>2</sup></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.099 / 0.703</td>\n</tr>\n\n</table>\n\n`````\n:::\n:::\n\n\nThis table includes:\n- Fixed effect estimates with 95% confidence intervals\n- Random effect variance components  \n- Model fit statistics (R²m and R²c)\n- Number of observations and groups\n\n### Creating figures\n\nWe have already used `ggeffects::ggpredict()` for predictions. You can customise these plots for presentation:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpredict(mixed_model, \n          terms = c(\"benzo_um\", \"group\"), \n          type = \"random\") |>  \n  plot(show_data = TRUE) + \n  scale_colour_brewer(palette = \"Dark2\") +\n  scale_fill_brewer(palette = \"Dark2\") +\n  facet_wrap(~group) +\n  labs(\n    x = \"Toxin concentration (µM)\",\n    y = \"Detoxification capacity\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![Customised prediction plot showing group-specific responses](intro-mixed-model_files/figure-html/unnamed-chunk-22-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n### Example write-up\n\n> We fitted a linear mixed model (estimated using REML and implemented in the `lmerTest` package) to examine the effect of dietary toxin concentration on larval detoxification capacity. The model included experimental batch as a random intercept to account for the repeated-measures experimental design. The model's conditional R² was 0.70, whilst the marginal R² was 0.10, indicating that experimental batch explained substantial variance beyond the effect of toxin concentration. Detoxification capacity increased by 2.03 units per µM increase in toxin (95% CI: 1.69–2.36; *t*~424~ = 11.9, *p* < 0.001).  Between-batch variance (σ² = 205) was approximately twice the residual variance (σ² = 101), confirming considerable baseline differences between experimental replicates.\n\n::: {.callout-tip}\n## Reporting checklist\n\nWhen reporting mixed model results, include:\n\n1. Model specification (which package, estimation method)\n2. Fixed effect estimates with 95% CIs and *p*-values\n3. Method for calculating degrees of freedom (Satterthwaite or Kenward-Roger)\n4. Variance components for random effects\n5. Model fit statistics (R²m and R²c)\n6. Number of observations and groups\n7. Statement about assumption checking\n:::\n\n\n## When to Use Each Approach\n\n**Use a pooled model when:**\n\n- Observations are genuinely independent\n- No grouping structure exists in the data\n\n**Use fixed effects for groups when:**\n\n- Few groups (< 5)\n- Large, balanced samples per group\n- You only want to make inferences about these specific groups\n- Groups represent treatments of direct interest\n\n**Use random effects when:**\n\n- Many groups (5+)\n- Unbalanced group sizes or missing data\n- You want to generalise to future groups\n- Groups represent nuisance variation to control for\n\n\n\n## Worked Example 1 - Dolphins\n\n### Deciding Between Fixed and Random Effects\n\nWhen building mixed models, use these questions to guide your decisions:\n\n1. **Are you directly interested in testing this effect?** → Fixed effect\n2. **Is the variable continuous?** → Fixed effect  \n3. **Does the variable have fewer than five levels?** → Fixed effect\n4. **Is the variable a grouping factor creating non-independence?** → Random effect\n\n### The Study\n\nThis dataset measured resting lung function in bottlenose dolphins. Researchers recorded tidal volume ($V_T$, in litres) as an index of lung capacity, measuring each dolphin between one and four times during both inhalation and exhalation.\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<a href=\"https://raw.githubusercontent.com/UEABIO/intro-mixed-models/main/book/files/dolphins.csv\">\n<button class=\"btn btn-success\"><i class=\"fa fa-save\"></i> Download Dolphins data</button>\n</a>\n```\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndolphins <- read_csv(\"files/dolphins.csv\") |>\n  mutate(direction = factor(direction)) |>\n  drop_na()\n```\n:::\n\n\n**Research question**: How does body mass affect tidal volume, and does this differ between inhalation and exhalation?\n\n**Variables**:\n- `vt`: Tidal volume (litres) - response variable\n- `bodymass`: Body mass (kg) - predictor of interest\n- `direction`: Breath direction (1 = exhalation, 2 = inhalation) - potential modifier\n- `animal`: Individual dolphin ID - creates non-independence\n\n::: {.task}\n:::: {.task-header}\nIdentify fixed and random effects\n::::\n:::: {.task-container}\n\nFor each variable, decide whether it should be a fixed or random effect:\n\n1. Body mass: <select class='webex-select'><option value='blank'></option><option value=''>Random Effect</option><option value='answer'>Fixed Effect</option></select>\n\n2. Direction: <select class='webex-select'><option value='blank'></option><option value=''>Random Effect</option><option value='answer'>Fixed Effect</option></select>\n\n3. Animal ID: <select class='webex-select'><option value='blank'></option><option value='answer'>Random Effect</option><option value=''>Fixed Effect</option></select>\n\n\n<div class='webex-solution'><button>Reasoning</button>\n\n\n1. **Body mass** - Fixed effect. We are directly interested in how body mass affects lung capacity (continuous variable, primary research question).\n\n2. **Direction** - Fixed effect. Only two levels (in/out), and we want to test whether the relationship differs by breath direction.\n\n3. **Animal ID** - Random effect. Individual dolphins were measured multiple times. If we ignored this, we would treat measurements from the same dolphin as independent (pseudoreplication). The random intercept accounts for individual variation in baseline lung capacity.\n\n\n</div>\n\n\n::::\n:::\n\n### Fitting the Model\n\nUsing the formula structure `y ~ fixed_effects + (1|random_effect)`:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(lmerTest)\n\ndolphmod <- lmer(vt ~ bodymass + direction + (1|animal), data = dolphins)\n```\n:::\n\n\nCheck the model summary:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(dolphmod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: vt ~ bodymass + direction + (1 | animal)\n   Data: dolphins\n\nREML criterion at convergence: 387.4\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-2.30795 -0.51983  0.04156  0.62404  2.26396 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n animal   (Intercept) 1.039    1.019   \n Residual             1.158    1.076   \nNumber of obs: 112, groups:  animal, 31\n\nFixed effects:\n             Estimate Std. Error        df t value Pr(>|t|)    \n(Intercept)  2.226398   0.627115 28.758081   3.550  0.00135 ** \nbodymass     0.016782   0.003259 26.720390   5.150  2.1e-05 ***\ndirection2   1.114821   0.203389 77.414421   5.481  5.1e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n           (Intr) bdymss\nbodymass   -0.927       \ndirection2 -0.162  0.000\n```\n\n\n:::\n:::\n\n\n**Random effects:**\n```\n Groups   Name        Variance Std.Dev.\n animal   (Intercept) 1.1293   1.0627  \n Residual             0.5664   0.7526  \n```\n\nIndividual dolphins vary in their baseline tidal volume (SD = 1.06 L). This accounts for 67% of residual variance [1.13/(1.13 + 0.57)], confirming that accounting for individual differences was important.\n\n**Fixed effects:**\n```\n              Estimate Std. Error       df t value Pr(>|t|)    \n(Intercept)  -3.025455   0.632299 29.40753  -4.785 4.72e-05 ***\nbodymass      0.015605   0.003743 29.40651   4.169 0.000249 ***\ndirection2    1.114655   0.204816 31.00000   5.443 6.24e-06 ***\n```\n\n- For every 1 kg increase in body mass, tidal volume increases by 0.016 L (95% CI: 0.008–0.024 L)\n- Inhalation has 1.11 L greater tidal volume than exhalation (95% CI: 0.71–1.52 L)\n\n### Visualising Predictions\n\nPopulation-level predictions using `emmeans`:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(emmeans)\n\n# Predictions at mean body mass for each breath direction\nemmeans(dolphmod, specs = \"direction\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n direction emmean    SE   df lower.CL upper.CL\n 1           5.26 0.235 42.6     4.78     5.73\n 2           6.37 0.235 42.6     5.90     6.84\n\nDegrees-of-freedom method: kenward-roger \nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Visualise the body mass effect\nemmeans(dolphmod, \n        specs = \"bodymass\",\n        at = list(bodymass = seq(130, 260, 10))) |>\n  as.data.frame() |>\n  ggplot(aes(x = bodymass, y = emmean)) +\n  geom_ribbon(aes(ymin = lower.CL, ymax = upper.CL), alpha = 0.3) +\n  geom_line(linewidth = 1) +\n  labs(\n    x = \"Body mass (kg)\",\n    y = \"Tidal volume (L)\"\n  )\n```\n\n::: {.cell-output-display}\n![Population-average relationship between body mass and tidal volume](intro-mixed-model_files/figure-html/unnamed-chunk-28-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nComparing breath directions:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggeffects)\n\nggpredict(dolphmod, \n          terms = c(\"bodymass\", \"direction\")) |>\n  plot(show_data = TRUE) +\n  labs(\n    x = \"Body mass (kg)\",\n    y = \"Tidal volume (L)\"\n  )\n```\n\n::: {.cell-output-display}\n![Effect of body mass differs by breath direction](intro-mixed-model_files/figure-html/unnamed-chunk-29-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n::: {.callout-note}\n## Reporting checklist\n\nWhen reporting this analysis, include:\n\n- Model specification: Linear mixed model with random intercepts for individual dolphins\n- Sample size: 32 dolphins, 1–4 measurements per individual\n- Fixed effect estimates with 95% CIs and *p*-values\n- Random effect variance components\n- Model fit (R²m and R²c)\n- Statement about assumptions\n:::\n\n---\n\n## Worked Example 2 - Nested Random Effects\n\n### Crossed vs Nested Designs\n\nWhen you have multiple random effects, they can be **crossed** or **nested**:\n\n**Crossed**: Levels of one grouping variable appear across all levels of another.\n- Example: Multiple woodlands studied across multiple years—every woodland appears in every year.\n- Formula: `(1|woodland) + (1|year)`\n\n**Nested**: Levels of one variable are unique within levels of another.\n- Example: Individual females are unique to specific woodlands—female ID only makes sense within its woodland.\n- Formula: `(1|woodland/female)`\n\n### The Study\n\nResearchers investigated whether experimental treatments affected liver glycogen levels in rats. The design was:\n\n- 3 treatments\n- 2 rats per treatment (6 rats total)\n- 3 liver samples per rat\n- 2 glycogen measurements per liver sample\n\nThis created **36 measurements total**, but these are not independent observations.\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<a href=\"https://raw.githubusercontent.com/UEABIO/intro-mixed-models/main/book/files/rats.rds\">\n<button class=\"btn btn-success\"><i class=\"fa fa-save\"></i> Download rats data</button>\n</a>\n```\n\n:::\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrats <- readRDS(\"rats.rds\")\n```\n:::\n\n\n**Sources of variation**:\n\n1. Measurement error within liver samples\n2. Heterogeneity between liver sections within a rat\n3. Individual variation between rats\n4. Treatment effects\n\n::: {.task}\n:::: {.task-header}\nUnderstanding the nested structure\n::::\n:::: {.task-container}\n\nExamine the data structure:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrats |>\n  aggregate(Glycogen ~ Rat + Treatment + Liver, data = _, mean) |>\n  head(12)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Rat |Treatment |Liver | Glycogen|\n|:---|:---------|:-----|--------:|\n|1   |1         |1     |    130.5|\n|2   |1         |1     |    149.0|\n|3   |2         |1     |    151.0|\n|4   |2         |1     |    153.0|\n|5   |3         |1     |    129.5|\n|6   |3         |1     |    139.0|\n|1   |1         |2     |    128.0|\n|2   |1         |2     |    141.5|\n|3   |2         |2     |    148.0|\n|4   |2         |2     |    147.0|\n|5   |3         |2     |    138.0|\n|6   |3         |2     |    138.5|\n\n</div>\n:::\n:::\n\n\n**Questions**:\n\n1. Are the liver sample IDs (1, 2, 3) the same piece of tissue across different rats?\n\n2. Is \"Liver 1\" from Rat 1 comparable to \"Liver 1\" from Rat 2?\n\n\n<div class='webex-solution'><button>Answer</button>\n\n\nNo. Each rat has its own three liver samples. \"Liver 1\" simply means \"the first sample taken from this particular rat\"—it's not the same anatomical location across rats. \n\nTherefore, liver samples are **nested within** individual rats. The coding (1, 2, 3) is reused for each rat, but these represent different physical samples.\n\n\n</div>\n\n\n::::\n:::\n\n### Fitting the Model\n\n**Incorrect approach** (treating effects as crossed):\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# WRONG - treats this as 2 rats and 3 liver types studied across all rats\nrats_wrong <- lmer(Glycogen ~ Treatment + (1|Rat) + (1|Liver), data = rats)\n```\n:::\n\n\nThis incorrectly assumes liver sample \"1\" is comparable across all rats.\n\n**Correct approach** (nested design):\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrats_correct <- lmer(Glycogen ~ Treatment + (1|Rat/Liver), data = rats)\nsummary(rats_correct)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: Glycogen ~ Treatment + (1 | Rat/Liver)\n   Data: rats\n\nREML criterion at convergence: 219.6\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-1.48212 -0.47263  0.03062  0.42934  1.82935 \n\nRandom effects:\n Groups    Name        Variance Std.Dev.\n Liver:Rat (Intercept) 14.17    3.764   \n Rat       (Intercept) 36.06    6.005   \n Residual              21.17    4.601   \nNumber of obs: 36, groups:  Liver:Rat, 18; Rat, 6\n\nFixed effects:\n            Estimate Std. Error      df t value Pr(>|t|)    \n(Intercept)  140.500      4.707   3.000  29.848 8.26e-05 ***\nTreatment2    10.500      6.657   3.000   1.577    0.213    \nTreatment3    -5.333      6.657   3.000  -0.801    0.482    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n           (Intr) Trtmn2\nTreatment2 -0.707       \nTreatment3 -0.707  0.500\n```\n\n\n:::\n:::\n\n\nThe formula `(1|Rat/Liver)` is equivalent to `(1|Rat) + (1|Rat:Liver)`, creating:\n- Random intercepts for each rat (accounting for individual variation)\n- Random intercepts for each liver sample within each rat (accounting for within-rat heterogeneity)\n\n**Random effects:**\n```\n Groups     Name        Variance Std.Dev.\n Liver:Rat  (Intercept) 18.333   4.282   \n Rat        (Intercept) 26.083   5.107   \n Residual               36.333   6.028   \n```\n\nCheck the number of groups matches your design:\n- 6 rats ✓\n- 18 liver samples (6 rats × 3 samples) ✓\n\n### Visualising Results\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpredict(rats_correct, terms = \"Treatment\") |>\n  plot()\n```\n\n::: {.cell-output-display}\n![Treatment effects on liver glycogen levels](intro-mixed-model_files/figure-html/unnamed-chunk-36-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpredict(rats_correct, \n          terms = c(\"Treatment\", \"Rat\"),\n          type = \"random\") |>\n  plot(show_data = TRUE)\n```\n\n::: {.cell-output-display}\n![Rat-specific predictions showing individual variation](intro-mixed-model_files/figure-html/unnamed-chunk-37-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n::: {.callout-warning}\n## Common mistake\n\nAlways check that the number of groups in your random effects summary matches your experimental design. If `(1|Rat)` shows 2 groups instead of 6, you've made a coding error.\n:::\n\n---\n\n## Worked Example 3 - Overdispersion in Binomial Models\n\n### The Problem\n\nBinomial GLMs assume variance follows a specific relationship with the mean. When observed variance exceeds this expectation (**overdispersion**), model assumptions are violated, leading to:\n\n- Underestimated standard errors\n- Overconfident *p*-values\n- Poor model fit\n\n**Common causes**: Variation between experimental batches, individual differences, clustered observations.\n\n### The Study\n\nResearchers investigated egg hatching rates in *Drosophila* crosses. The experimental design involved:\n\n- Different genetic crosses\n- Multiple replicate experiments\n- Multiple females per replicate\n- Egg batches from each female\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<a href=\"https://raw.githubusercontent.com/Philip-Leftwich/Oct-Intro-Analytics/refs/heads/dev/files/egg_hatch_mixed.csv\">\n<button class=\"btn btn-success\"><i class=\"fa fa-save\"></i> Download Egg Hatching data</button>\n</a>\n```\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n::: {.task}\n:::: {.task-header}\nFit a standard Binomial GLM\n::::\n:::: {.task-container}\n\nCreate the success/failure response variable and fit a binomial model:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\negg_hatch_data <- egg_hatch_data |>\n  mutate(unhatched_eggs = number_of_eggs - number_of_larvae)\n\nbinomial_model <- glm(\n  cbind(number_of_larvae, unhatched_eggs) ~ cross,\n  family = binomial,\n  data = egg_hatch_data\n)\n\nsummary(binomial_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = cbind(number_of_larvae, unhatched_eggs) ~ cross, \n    family = binomial, data = egg_hatch_data)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  1.05143    0.04658  22.573  < 2e-16 ***\ncrossB       0.38815    0.09124   4.254  2.1e-05 ***\ncrossC       1.29224    0.11812  10.940  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1307.6  on 54  degrees of freedom\nResidual deviance: 1157.3  on 52  degrees of freedom\nAIC: 1363.6\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\nCheck for overdispersion:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nperformance::check_overdispersion(binomial_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Overdispersion test\n\n dispersion ratio =   1.703\n          p-value = < 0.001\n```\n\n\n:::\n:::\n\n\n\n<div class='webex-solution'><button>Expected output</button>\n\n```\n# Overdispersion test\n       dispersion ratio =   4.832\n  Pearson's Chi-Squared = 289.934\n                p-value =  < 0.001\n```\n\nDispersion ratio >> 1 indicates severe overdispersion.\n\n\n</div>\n\n\nExamine model diagnostics:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nperformance::check_model(binomial_model)\n```\n:::\n\n\n**Problems**: Outliers, poor quantile distribution, systematic under-prediction.\n\n::::\n:::\n\n### Using Random Effects to Account for Overdispersion\n\n::: {.task}\n:::: {.task-header}\nFit Binomial GLMMs\n::::\n:::: {.task-container}\n\n**Question**: Which variables create non-independence in this dataset?\n\n\n<div class='webex-solution'><button>Answer</button>\n\n\n- **Replicate**: Experiments conducted on different days may have different baseline hatching rates\n- **Female**: Multiple egg batches from the same female are not independent\n- **Nesting**: Female IDs are unique within each replicate (nested structure)\n\n\n</div>\n\n\nFit models with different random effect structures:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(lme4)\n\n# Random intercept for replicate only\nbinomial_mixed_rep <- glmer(\n  cbind(number_of_larvae, unhatched_eggs) ~ cross + (1|replicate),\n  family = binomial,\n  data = egg_hatch_data\n)\n\n# Random intercepts for replicate AND female (nested)\nbinomial_mixed_rep_fem <- glmer(\n  cbind(number_of_larvae, unhatched_eggs) ~ cross + (1|replicate/female_num),\n  family = binomial,\n  data = egg_hatch_data\n)\n```\n:::\n\n\nCompare models:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nAIC(binomial_model, binomial_mixed_rep, binomial_mixed_rep_fem)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|                       | df|      AIC|\n|:----------------------|--:|--------:|\n|binomial_model         |  3| 1363.551|\n|binomial_mixed_rep     |  4| 1263.221|\n|binomial_mixed_rep_fem |  5|  644.059|\n\n</div>\n:::\n:::\n\n\n\nCheck overdispersion in the best model:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nperformance::check_overdispersion(binomial_mixed_rep_fem)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Overdispersion test\n\n dispersion ratio = 1.153\n          p-value = 0.224\n```\n\n\n:::\n:::\n\n\n\n<div class='webex-solution'><button>Expected output</button>\n\n\nOverdispersion resolved ✓\n\n\n</div>\n\n\nExamine the random effects:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(binomial_mixed_rep_fem)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeneralized linear mixed model fit by maximum likelihood (Laplace\n  Approximation) [glmerMod]\n Family: binomial  ( logit )\nFormula: \ncbind(number_of_larvae, unhatched_eggs) ~ cross + (1 | replicate/female_num)\n   Data: egg_hatch_data\n\n     AIC      BIC   logLik deviance df.resid \n   644.1    654.1   -317.0    634.1       50 \n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-5.2142 -0.9049  0.0332  1.0933  6.0739 \n\nRandom effects:\n Groups               Name        Variance Std.Dev.\n female_num:replicate (Intercept) 1.71879  1.3110  \n replicate            (Intercept) 0.01343  0.1159  \nNumber of obs: 55, groups:  female_num:replicate, 34; replicate, 5\n\nFixed effects:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)   1.2471     0.2426   5.140 2.74e-07 ***\ncrossB        0.9274     0.1341   6.916 4.65e-12 ***\ncrossC        0.6958     0.1464   4.752 2.02e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n       (Intr) crossB\ncrossB -0.131       \ncrossC -0.145  0.146\n```\n\n\n:::\n:::\n\n\n\n**Interpretation**: \n\n- Most variation is **between females** (SD = 0.53)\n- Very little variation **between replicates** (SD = 0.11)\n- But the nested structure `(1|replicate/female_num)` is essential because female IDs are only meaningful within their replicate\n\nCheck the number of groups:\n```\nNumber of obs: 60, groups:  female_num:replicate, 20; replicate, 3\n```\n\nThis matches the design: 3 replicates, ~7 females per replicate ✓\n\n::::\n:::\n\n### Visualising Results\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpredict(binomial_mixed_rep_fem, terms = \"cross\") |>\n  plot()\n```\n\n::: {.cell-output-display}\n![Cross effects on hatching probability (population average)](intro-mixed-model_files/figure-html/unnamed-chunk-47-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n::: {.callout-tip}\n## Key lesson\n\nWhen binomial or Poisson GLMs show overdispersion, consider whether random effects can account for the extra-binomial/extra-Poisson variation. If your data have a hierarchical structure (batches, individuals, blocks), random intercepts often resolve overdispersion by modelling the source of extra variance.\n:::\n\n## Summary\n\n### When Should I Use Mixed Models?\n\nUse this decision guide to determine the best approach for your data:\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"grViz html-widget html-fill-item\" id=\"htmlwidget-25b10a12e3caf1923a6f\" style=\"width:100%;height:480px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-25b10a12e3caf1923a6f\">{\"x\":{\"diagram\":\"\\ndigraph decision_tree {\\n  \\n  graph [rankdir = TB, fontsize = 10]\\n  \\n  node [shape = box, style = rounded, fontname = Helvetica]\\n  \\n  start [label = \\\"Do observations come\\nfrom distinct groups?\\\", shape = diamond]\\n  q1 [label = \\\"Are groups experimental\\ntreatments of interest?\\\", shape = diamond]\\n  q2 [label = \\\"Are there 5+ groups\\nsampled randomly?\\\", shape = diamond]\\n \\n  \\n  pool [label = \\\"Pool observations\\n(standard linear model)\\\", shape = ellipse]\\n  fixed [label = \\\"Use Fixed Effects\\\", shape = ellipse]\\n  random [label = \\\"Use Random Effects\\n(Mixed model)\\\", shape = ellipse]\\n  \\n  start -> pool [label = \\\"No\\\"]\\n  start -> q1 [label = \\\"Yes\\\"]\\n  q1 -> fixed [label = \\\"Yes\\\"]\\n  q1 -> q2 [label = \\\"No\\\"]\\n  q2 -> random [label = \\\"Yes\\\"]\\n  q2 -> fixed [label = \\\"No\\\"]\\n\\n}\\n\",\"config\":{\"engine\":\"dot\",\"options\":null}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n\nDecision tree for choosing between pooled, fixed, and random effects\n:::\n:::\n\n\n### Quick Reference Table\n\n| Your Situation | What To Do | Example |\n|----------------|------------|---------|\n| Experimental treatments you want to compare | **Fixed effects** | Comparing 3 diet treatments |\n| Many randomly sampled groups (5+) | **Random effects** | 20 field sites, 50 individual animals |\n| Few groups (< 5) creating non-independence | **Fixed effects** | 3 experimental batches |\n| Truly independent observations | **Pool (standard model)** | Single measurement per individual |\n| Repeated measures on individuals | **Random effects** | Multiple measurements per person over time |\n| Nested structure (samples within groups) | **Random effects (nested)** | Liver samples within rats |\n\n\n### Common Issues and Solutions\n\n**Singular fit warning**: `boundary (singular) fit: see help('isSingular')`\n\nYour model fitted, but one or more random effects have estimated variance near zero. This suggests:\n\n- The random effect explains very little variance (perhaps not needed)\n- You may have too few groups for that random effect\n- The model may be overparameterised (too complex for your data)\n\n**What to do**: \n- Check if the random effect variance is close to zero in `summary()`\n- Consider removing random effects with near-zero variance\n- Try a simpler random effects structure\n\n**Convergence warnings**: The optimisation algorithm failed to find the best parameter estimates.\n\n**Solutions** (try in this order):\n\n1. **Rescale continuous predictors**: Large differences in variable scales can cause convergence problems.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata <- data |>\n  mutate(predictor_scaled = scale(predictor))\n\n# Refit with scaled predictor\nmodel <- lmer(response ~ predictor_scaled + (1|group), data = data)\n```\n:::\n\n\n2. **Try a different optimiser**:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel <- lmer(response ~ predictor + (1|group), \n              data = data,\n              control = lmerControl(optimizer = \"bobyqa\"))\n```\n:::\n\n\n3. **Simplify the model**: Remove random slopes or interactions if present, keeping only random intercepts.\n\n4. **Check your data**: Ensure there are no coding errors, sufficient observations per group, and reasonable variance in predictors.\n\n::: {.callout-warning}\n## Convergence warnings are serious\n\nUnlike singular fit warnings, convergence failures mean the model results are unreliable. Do not interpret or report a model that failed to converge without first resolving the issue.\n:::\n\n### Key Concepts to Remember\n\n1. **Mixed models account for non-independence** created by grouping structures in your data\n\n2. **Random effects model variance**, not specific group means\n\n3. **Fixed effects are appropriate when**:\n   - You have few groups (< 5)\n   - Groups represent treatments you want to compare\n   - You only want to make inferences about these specific groups\n\n4. **Random effects are appropriate when**:\n   - You have many groups (5+)\n   - Groups are randomly sampled from a larger population\n   - You want to generalise to new groups\n   - Design is unbalanced or has missing data\n\n5. **Model checking is essential**: Always verify assumptions using diagnostic plots before interpreting results\n\n6. **Report thoroughly**: Include sample sizes, number of groups, variance components, fixed effect estimates with CIs, and model fit statistics\n\n### Further Reading\n\nEssential resources for deepening your understanding:\n\n- [A brief introduction to mixed effects modelling and multi-model inference in ecology](https://peerj.com/articles/4794/) - Accessible introduction with ecological examples\n\n- [Perils and pitfalls of mixed-effects regression models in biology](https://peerj.com/articles/9522/) - Common mistakes and how to avoid them\n\n- [Is it a fixed or random effect?](https://dynamicecology.wordpress.com/2015/11/04/is-it-a-fixed-or-random-effect/) - Blog post clarifying a persistent confusion\n\n- [Mixed Effects Models and Extensions in Ecology with R](https://link.springer.com/book/10.1007/978-0-387-87458-6) - Comprehensive textbook (advanced)\n\n::: {.callout-note}\n## Practice makes perfect\n\nThe best way to become comfortable with mixed models is to practice with your own data. Start simple with random intercepts only, verify your models fit properly, then gradually increase complexity as needed.\n:::\n",
    "supporting": [
      "intro-mixed-model_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/font-awesome-6.5.2/js/script.js\"></script>\n<link href=\"site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"site_libs/viz-1.8.2/viz.js\"></script>\n<link href=\"site_libs/DiagrammeR-styles-0.2/styles.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/grViz-binding-1.0.11/grViz.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}